# Example parameter file, see parameters_launch.py

# Format is namespace_name/node_name
bluerov2/gscam_publisher:
  ros__parameters:
    gscam_config: "v4l2src device=/dev/video0 ! image/jpeg,width=1920,height=1080,framerate=30/1"
    image_encoding: "jpeg"
    preroll: False
    use_gst_timestamps: False
    frame_id: 'bluerov2_fpv_link'